name: Run Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_TOKEN: "dummy-token"
      GITHUB_REPOSITORY: "owner/repo"
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: make setup
    
    - name: Run tests
      run: make test
    
    - name: Generate coverage report
      run: make test_coverage 